disabled_rules:
- trailing_whitespace
- nesting
- missing_docs

opt_in_rules:
#- array_init
#- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
#- discouraged_optional_collection
- empty_count
- empty_string
- empty_xctest_method
#- explicit_acl
#- explicit_enum_raw_value
- explicit_init
#- explicit_top_level_acl
#- explicit_type_interface
#- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
- file_name
- first_where
- force_unwrapping
- function_default_parameter_at_end
- identical_operands
#- implicit_return
- implicitly_unwrapped_optional
#- indentation_width
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
#- lower_acl_than_parent
#- missing_docs
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
#- no_grouping_extension
#- number_separator
#- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
#- prefixed_toplevel_constant
- private_action
- private_outlet
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
#- quick_discouraged_focused_test
#- quick_discouraged_pending_test
- redundant_nil_coalescing
- redundant_type_annotation
- required_enum_case
- single_test_class
- sorted_first_last
#- sorted_imports
#- strict_fileprivate
#- switch_case_on_newline
#- trailing_closure
- toggle_bool
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
#- vertical_parameter_alignment_on_call
- yoda_condition

excluded:
- BUUTSHorenkoTests

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
